print ('IMC')
print('')
p=int(input('Peso: '))
a=float(input('Altura (.*): '))
e=a*a
f=p/e
print('seu IMC é de:',f)
print('')
print('Menor do que 18,5 = abaixo do peso')
print('')
print('entre 18,5 e 24,9 = peso normal')
print('')
print('entre 25 e 29,9 = acima do peso (sobrepeso)')
print('')
print('entre 30 e 34,9 = obesidade 1')
print('')
print('entre 35 e 39,9 = obesidade 2')
print('')
print('maior do que 40 = obesidade 3')